import type { RequiredDataFromCollectionSlug } from 'payload'

const FORD_SERVICE_MODELS = [
  'Everest',
  'Mustang Dark Horse',
  'Mustang GT',
  'New Level Territory',
  'New Tourneo Custom',
  'New Transit Custom',
  'Next Level Everest',
  'Next Level Ranger',
  'Ranger',
  'Ranger Platinum',
  'Ranger Raptor',
  'Ranger Single Cab',
  'Ranger Sport',
  'Ranger Super Cab',
  'Ranger Tremor',
  'Ranger Wildtrak',
  'Ranger Wildtrak X',
  'Ranger XL',
  'Ranger XLT',
  'Transit Van',
  'Other',
].map((model) => ({ label: model, value: model }))

export const serviceBookingForm: RequiredDataFromCollectionSlug<'forms'> = {
  title: 'Service Booking Form',
  confirmationType: 'message',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          tag: 'h2',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Booking Request Received',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Thank you! A member of our service team will be in touch shortly to confirm your appointment.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  emails: [
    {
      emailFrom: '"Eagle Ford" <noreply@eagleford.co.za>',
      emailTo: '{{email}}',
      subject: 'Your service booking request has been received — Eagle Ford',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Thank you! A member of our service team will be in touch shortly to confirm your appointment.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],
  submitButtonLabel: 'Submit',
  fields: [
    {
      blockType: 'text',
      blockName: 'firstName',
      name: 'firstName',
      label: 'First Name',
      required: true,
      width: 50,
    },
    {
      blockType: 'text',
      blockName: 'lastName',
      name: 'lastName',
      label: 'Last Name',
      required: true,
      width: 50,
    },
    {
      blockType: 'text',
      blockName: 'phone',
      name: 'phone',
      label: 'Phone Number',
      required: true,
      width: 50,
    },
    {
      blockType: 'email',
      blockName: 'email',
      name: 'email',
      label: 'Email Address',
      required: true,
      width: 50,
    },
    {
      blockType: 'text',
      blockName: 'registration',
      name: 'registration',
      label: 'Registration Number',
      required: true,
      width: 50,
    },
    {
      blockType: 'text',
      blockName: 'vin',
      name: 'vin',
      label: 'VIN Number',
      required: false,
      width: 50,
    },
    {
      blockType: 'number',
      blockName: 'mileage',
      name: 'mileage',
      label: 'Mileage (km)',
      required: false,
      width: 50,
    },
    {
      blockType: 'date',
      blockName: 'preferredDate',
      name: 'preferredDate',
      label: 'Preferred Service Date',
      required: true,
      width: 50,
    },
    {
      blockType: 'select',
      blockName: 'model',
      name: 'model',
      label: 'Model',
      placeholder: 'What model would you like to service?',
      required: true,
      width: 100,
      options: FORD_SERVICE_MODELS,
    },
    {
      blockType: 'checkbox',
      blockName: 'privacyPolicy',
      name: 'privacyPolicy',
      label: 'I have read and agree to the Eagle Ford (Pty) Ltd Privacy Policy',
      required: true,
      width: 100,
    },
  ],
}
