import type { RequiredDataFromCollectionSlug } from 'payload'

export const vehicleQuoteForm: RequiredDataFromCollectionSlug<'forms'> = {
  title: 'Vehicle Quote',
  confirmationType: 'message',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          tag: 'h2',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Enquiry Received',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Thank you for your interest. A member of our sales team will be in touch with you shortly.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  emails: [
    {
      emailFrom: '"Eagle Ford" <noreply@eagleford.co.za>',
      emailTo: '{{email}}',
      subject: 'Your vehicle quote enquiry has been received — Eagle Ford',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Thank you for your interest. A member of our sales team will be in touch with you shortly.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    {
      emailFrom: '"Eagle Ford" <noreply@eagleford.co.za>',
      emailTo: 'sales@eagleford.co.za',
      subject: 'Vehicle quote enquiry: {{vehicleName}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'A new vehicle quote enquiry has been submitted.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Vehicle: {{vehicleName}}',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Name: {{firstName}} {{lastName}}',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Phone: {{phone}}',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Email: {{email}}',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Message: {{message}}',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],
  submitButtonLabel: 'Submit Enquiry',
  fields: [
    {
      blockType: 'text',
      blockName: 'vehicleName',
      name: 'vehicleName',
      label: 'Vehicle',
      required: false,
      width: 100,
    },
    {
      blockType: 'text',
      blockName: 'firstName',
      name: 'firstName',
      label: 'First Name',
      required: true,
      width: 50,
    },
    {
      blockType: 'text',
      blockName: 'lastName',
      name: 'lastName',
      label: 'Last Name',
      required: true,
      width: 50,
    },
    {
      blockType: 'text',
      blockName: 'phone',
      name: 'phone',
      label: 'Phone Number',
      required: true,
      width: 50,
    },
    {
      blockType: 'email',
      blockName: 'email',
      name: 'email',
      label: 'Email Address',
      required: true,
      width: 50,
    },
    {
      blockType: 'textarea',
      blockName: 'message',
      name: 'message',
      label: 'Question / Comment',
      required: false,
      width: 100,
    },
    {
      blockType: 'checkbox',
      blockName: 'privacyPolicy',
      name: 'privacyPolicy',
      label: 'I have read and agree to the Eagle Ford (Pty) Ltd Privacy Policy',
      required: true,
      width: 100,
    },
  ],
}
