import type { BlockSlug } from 'payload'

/** Element blocks — mount inside Section/Wrapper/Column (v2) only. */
export const elementV2ContentRefs: BlockSlug[] = [
  'buttonV2',
  'cardV2',
  'accordionV2',
  'imageV2',
  'separatorV2',
  'formV2',
  'iconV2',
  'videoV2',
  'quoteV2',
  'spacerV2',
  'heroV2',
  'mapV2',
  'faqV2',
  'stockArchiveV2',
  'carouselV2',
  'specialsArchiveV2',
  'vehicleCatalogV2',
  'galleryV2',
  'featureListV2',
  'featureRowsV2',
  'popupCardsV2',
  'statsV2',
  'teamGridV2',
  'hoursTabsV2',
  'contactInfoV2',
  'contactFooterV2',
  'financeCalculatorV2',
  'reviewsV2',
]
