/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavLinks".
 */
export type NavLinks =
  | {
      type?: ('reference' | 'custom' | 'dropdown') | null;
      variant?: ('link' | 'button') | null;
      target?: ('_blank' | '_self' | '_parent' | '_top') | null;
      label?: string | null;
      reference?: {
        relationTo: 'pages';
        value: string | Page;
      } | null;
      url?: string | null;
      /**
       * Optional link for the parent menu label
       */
      parentLinkType?: ('none' | 'reference' | 'custom') | null;
      children?:
        | {
            type?: ('reference' | 'custom') | null;
            label?: string | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
            id?: string | null;
          }[]
        | null;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    section: Section;
    sectionInner: SectionInner;
    hero: Hero;
    heading: Heading;
    'rich-text': RichText;
  };
  collections: {
    users: User;
    pages: Page;
    blogs: Blog;
    media: Media;
    categories: Category;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    settings: Setting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "section".
 */
export interface Section {
  content?: (SectionInner | Heading | Hero | RichText)[] | null;
  backgroundColor?:
    | ('none' | 'white' | 'light' | 'neutral' | 'primary-light' | 'primary' | 'secondary' | 'dark')
    | null;
  /**
   * Diagonal clip on the section background. Pair with a background color for best results.
   */
  backgroundStyle?: ('none' | 'slanted') | null;
  container?: boolean | null;
  gridCols?: ('1' | '2' | '3' | '4') | null;
  /**
   * Adds a vertical divider between columns.
   */
  showDivider?: boolean | null;
  dividerColor?: ('primary' | 'secondary' | 'neutral') | null;
  layout?: {
    /**
     * Padding and margin per breakpoint (top, right, bottom, left).
     */
    spacing?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  accessibility?: {
    /**
     * Sets the semantic HTML element or ARIA landmark role. "region" requires a label to be announced by screen readers.
     */
    landmark?:
      | ('' | 'main' | 'region' | 'banner' | 'contentinfo' | 'navigation' | 'complementary' | 'search' | 'form')
      | null;
    /**
     * Provides a human-readable, localised description of the element's role (aria-roledescription). Overrides how assistive technology announces the landmark role — e.g. "Promotional banner" instead of "region". Use sparingly; requires a meaningful role to be set.
     */
    ariaRoleDescription?: string | null;
    /**
     * Provides an accessible name for the section (aria-label). Required when using "region" landmark and no visible heading is present.
     */
    ariaLabel?: string | null;
    /**
     * References the ID of a visible heading element that labels this section (aria-labelledby). Preferred over ARIA Label when a heading exists.
     */
    ariaLabelledBy?: string | null;
    /**
     * References the ID of an element that provides an extended description of this section (aria-describedby).
     */
    ariaDescribedBy?: string | null;
    /**
     * Hides this section entirely from screen readers. Use only for purely decorative sections that add no informational value.
     */
    ariaHidden?: boolean | null;
    /**
     * Sets the HTML id attribute. Used as an anchor target and can be referenced by aria-labelledby / aria-describedby on other elements.
     */
    id?: string | null;
    /**
     * Controls whether the section itself is focusable. Rarely needed — only set if the section is a scroll target or managed focus container.
     */
    tabIndex?: ('' | '0' | '-1') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectionInner".
 */
export interface SectionInner {
  content?: (Heading | Hero | RichText)[] | null;
  backgroundColor?:
    | ('none' | 'white' | 'light' | 'neutral' | 'primary-light' | 'primary' | 'secondary' | 'dark')
    | null;
  /**
   * Diagonal clip on the section background. Pair with a background color for best results.
   */
  backgroundStyle?: ('none' | 'slanted') | null;
  container?: boolean | null;
  /**
   * Aligns content vertically within the block. Most effective when used inside a Row block.
   */
  verticalAlign?: ('top' | 'center' | 'bottom') | null;
  layout?: {
    /**
     * Padding and margin per breakpoint (top, right, bottom, left).
     */
    spacing?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  accessibility?: {
    /**
     * Sets the semantic HTML element or ARIA landmark role. "region" requires a label to be announced by screen readers.
     */
    landmark?:
      | ('' | 'main' | 'region' | 'banner' | 'contentinfo' | 'navigation' | 'complementary' | 'search' | 'form')
      | null;
    /**
     * Provides a human-readable, localised description of the element's role (aria-roledescription). Overrides how assistive technology announces the landmark role — e.g. "Promotional banner" instead of "region". Use sparingly; requires a meaningful role to be set.
     */
    ariaRoleDescription?: string | null;
    /**
     * Provides an accessible name for the section (aria-label). Required when using "region" landmark and no visible heading is present.
     */
    ariaLabel?: string | null;
    /**
     * References the ID of a visible heading element that labels this section (aria-labelledby). Preferred over ARIA Label when a heading exists.
     */
    ariaLabelledBy?: string | null;
    /**
     * References the ID of an element that provides an extended description of this section (aria-describedby).
     */
    ariaDescribedBy?: string | null;
    /**
     * Hides this section entirely from screen readers. Use only for purely decorative sections that add no informational value.
     */
    ariaHidden?: boolean | null;
    /**
     * Sets the HTML id attribute. Used as an anchor target and can be referenced by aria-labelledby / aria-describedby on other elements.
     */
    id?: string | null;
    /**
     * Controls whether the section itself is focusable. Rarely needed — only set if the section is a scroll target or managed focus container.
     */
    tabIndex?: ('' | '0' | '-1') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionInner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heading".
 */
export interface Heading {
  template: 'separator' | 'standard' | 'dash' | 'swipe';
  standardHeadingContent?: StandardHeading;
  dashHeadingContent?: DashHeading;
  separatorHeadingContent?: SeparatorHeading;
  swipeHeadingContent?: SwipeHeading;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StandardHeading".
 */
export interface StandardHeading {
  tag?: {
    label?: string | null;
    style?: ('filled' | 'outline' | 'none') | null;
    color?: ('primary' | 'neutral' | 'success' | 'danger' | 'warning' | 'white') | null;
  };
  /**
   * Wrap text in <accent-under>text</accent-under> for a primary underline accent, or <accent-under color="#RRGGBB">text</accent-under> for a custom color. Also supports <color=#RRGGBB>text</color>.
   */
  heading: string;
  /**
   * Animates the main heading with a word-by-word reveal.
   */
  splitTextAnimation?: boolean | null;
  /**
   * Wrap text in <accent-under>text</accent-under> for a primary underline accent, or <accent-under color="#RRGGBB">text</accent-under> for a custom color. Also supports <color=#RRGGBB>text</color>.
   */
  subheading?: string | null;
  headingTag?: ('h1' | 'h2' | 'h3' | 'h4') | null;
  size?: ('sm' | 'md' | 'lg' | 'xl') | null;
  alignment?: ('left' | 'center' | 'right') | null;
  color?: ('primary' | 'neutral' | 'success' | 'danger' | 'warning' | 'white') | null;
  fontWeight?: ('normal' | 'medium' | 'semibold' | 'bold' | 'extrabold') | null;
  uppercase?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DashHeading".
 */
export interface DashHeading {
  tag: string;
  /**
   * Wrap text in <accent-under>text</accent-under> for a primary underline accent, or <accent-under color="#RRGGBB">text</accent-under> for a custom color. Also supports <color=#RRGGBB>text</color>.
   */
  heading: string;
  /**
   * Wrap text in <accent-under>text</accent-under> for a primary underline accent, or <accent-under color="#RRGGBB">text</accent-under> for a custom color. Also supports <color=#RRGGBB>text</color>.
   */
  subheading?: string | null;
  headingTag?: ('h1' | 'h2' | 'h3' | 'h4') | null;
  size?: ('sm' | 'md' | 'lg' | 'xl') | null;
  alignment?: ('left' | 'center' | 'right') | null;
  color?: ('primary' | 'neutral' | 'success' | 'danger' | 'warning' | 'white') | null;
  fontWeight?: ('normal' | 'medium' | 'semibold' | 'bold' | 'extrabold') | null;
  uppercase?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeparatorHeading".
 */
export interface SeparatorHeading {
  /**
   * Wrap text in <accent-under>text</accent-under> for a primary underline accent, or <accent-under color="#RRGGBB">text</accent-under> for a custom color. Also supports <color=#RRGGBB>text</color>.
   */
  heading: string;
  headingTag?: ('h1' | 'h2' | 'h3' | 'h4') | null;
  size?: ('sm' | 'md' | 'lg' | 'xl') | null;
  alignment?: ('left' | 'center' | 'right') | null;
  color?: ('primary' | 'neutral' | 'success' | 'danger' | 'warning' | 'white') | null;
  fontWeight?: ('normal' | 'medium' | 'semibold' | 'bold' | 'extrabold') | null;
  uppercase?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SwipeHeading".
 */
export interface SwipeHeading {
  /**
   * Wrap text in <accent-under>text</accent-under> for a primary underline accent, or <accent-under color="#RRGGBB">text</accent-under> for a custom color. Also supports <color=#RRGGBB>text</color>.
   */
  heading: string;
  /**
   * Hex color for the reveal bar (e.g. #FF0000)
   */
  barColor?: string | null;
  headingTag?: ('h1' | 'h2' | 'h3' | 'h4') | null;
  size?: ('sm' | 'md' | 'lg' | 'xl') | null;
  alignment?: ('left' | 'center' | 'right') | null;
  color?: ('primary' | 'neutral' | 'success' | 'danger' | 'warning' | 'white') | null;
  fontWeight?: ('normal' | 'medium' | 'semibold' | 'bold' | 'extrabold') | null;
  uppercase?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  template:
    | 'form'
    | 'cta'
    | 'video-banner'
    | 'banner'
    | 'carousel'
    | 'dictionary'
    | 'grid'
    | 'wave'
    | 'portrait-punch'
    | 'headline';
  ctaHeroContent?: CtaHero;
  dictionaryHeroContent?: DictionaryHero;
  gridHeroContent?: GridHero;
  carouselHeroContent?: CarouselHero;
  bannerHeroContent?: BannerHero;
  videoBannerHeroContent?: VideoBannerHero;
  waveHero?: WaveHero;
  portraitPunchHeroContent?: PortraitPunchHero;
  headlineHeroContent?: HeadlineHero;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaHero".
 */
export interface CtaHero {
  /**
   * Recommended: vehicle or product on a dark/transparent background for the right side of the banner.
   */
  image: string | Media;
  heading: string;
  paragraph?: string | null;
  cta?: NavLinks;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  creditText?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * When enabled, the header is transparent at the top of the page (for hero blocks) and turns solid white on scroll. When disabled (default), the header is always solid white with dark navigation links.
   */
  overlayHeader?: boolean | null;
  content?: {
    section?: Section[] | null;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DictionaryHero".
 */
export interface DictionaryHero {
  mainImage?: (string | null) | Media;
  mainHeading?: string | null;
  subHeading?: string | null;
  definitions?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  exampleText?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GridHero".
 */
export interface GridHero {
  mainHeading: string;
  subHeading?: string | null;
  description?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselHero".
 */
export interface CarouselHero {
  slides: {
    /**
     * Recommended: 1920×1080px, WebP or JPEG.
     */
    image: string | Media;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    id?: string | null;
  }[];
  enableInteraction?: boolean | null;
  autoPlay?: boolean | null;
  /**
   * Time in milliseconds between slide transitions.
   */
  autoPlayInterval?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerHero".
 */
export interface BannerHero {
  bannerTemplate: 'full-width' | 'overlay';
  fullWidthBannerContent?: FullWidthBanner;
  overlayBannerContent?: OverlayBanner;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullWidthBanner".
 */
export interface FullWidthBanner {
  /**
   * Recommended: wide format (e.g. 1920×600px), WebP or JPEG.
   */
  image: string | Media;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OverlayBanner".
 */
export interface OverlayBanner {
  /**
   * Recommended: wide format (e.g. 1920×600px), WebP or JPEG.
   */
  image: string | Media;
  heading?: string | null;
  subheading?: string | null;
  alignment?: ('left' | 'center' | 'right') | null;
  /**
   * Adds a semi-transparent dark tint over the image to improve text legibility.
   */
  darkOverlay?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBannerHero".
 */
export interface VideoBannerHero {
  /**
   * Recommended: MP4 or WebM, wide format (e.g. 1920×600).
   */
  video: string | Media;
  /**
   * Shown until the page has fully loaded, then replaced by autoplaying video.
   */
  poster: string | Media;
  loop?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WaveHero".
 */
export interface WaveHero {
  slides?:
    | {
        /**
         * Recommended: 1920×1080px, WebP or JPEG.
         */
        image: string | Media;
        /**
         * Tint over the background image. Choose None to disable.
         */
        overlayColor?: ('none' | 'primary' | 'secondary' | 'dark' | 'danger') | null;
        /**
         * Overlay strength (0–100). Set to 0 for no overlay.
         */
        overlayOpacity?: number | null;
        /**
         * Wrap text in <accent-under>text</accent-under> for a primary underline accent, or <accent-under color="#RRGGBB">text</accent-under> for a custom color. Also supports <color=#RRGGBB>text</color>.
         */
        title: string;
        /**
         * Wrap text in <accent-under>text</accent-under> for a primary underline accent, or <accent-under color="#RRGGBB">text</accent-under> for a custom color. Also supports <color=#RRGGBB>text</color>.
         */
        subtitle?: string | null;
        primaryLink?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  showWave?: boolean | null;
  autoPlay?: boolean | null;
  /**
   * Time in milliseconds between slide transitions.
   */
  autoPlayInterval?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortraitPunchHero".
 */
export interface PortraitPunchHero {
  heading: string;
  subheading?: string | null;
  /**
   * Recommended: portrait format (e.g. 3:4 ratio, ~800×1066px), WebP or JPEG.
   */
  image: string | Media;
  overlayColor?: ('none' | 'primary' | 'secondary' | 'black' | 'white') | null;
  /**
   * Percentage opacity of the overlay. Only applied when a color is selected.
   */
  overlayOpacity?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadlineHero".
 */
export interface HeadlineHero {
  /**
   * Wrap text in <accent-under>text</accent-under> for a primary underline accent, or <accent-under color="#RRGGBB">text</accent-under> for a custom color. Also supports <color=#RRGGBB>text</color>.
   */
  mainHeading: string;
  subHeading?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rich-text".
 */
export interface RichText {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'rich-text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  username?: string | null;
  roles?: ('admin' | 'contributor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Blog)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'blogs';
          value: string | Blog;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'blogs';
    value: string | Blog;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'blogs';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  username?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  overlayHeader?: T;
  content?:
    | T
    | {
        section?: T | {};
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  creditText?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  headerLogo?: (string | null) | Media;
  topNav?: {
    homeLinkText?: string | null;
    topNavLinks?: NavLinks;
  };
  leftLinks?: NavLinks;
  rightLinks?: NavLinks;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Copyright text shown in the footer bottom bar.
   */
  copyrightText?: string | null;
  bottomBarLink?: NavLinks;
  /**
   * Full WhatsApp chat URL (e.g. https://wa.me/27123456789). Shows a floating button when set.
   */
  whatsappUrl?: string | null;
  newsletter?: {
    enabled?: boolean | null;
    heading?: string | null;
    placeholder?: string | null;
    buttonLabel?: string | null;
    /**
     * Single-step form with one email field (field name e.g. email). Submissions appear under Form Submissions.
     */
    form?: (string | null) | Form;
  };
  /**
   * Add up to 6 footer columns. Drag to reorder. Each column type has its own set of fields.
   */
  columns?:
    | (
        | {
            /**
             * Column heading displayed above the list of links.
             */
            heading: string;
            links?: NavLinks;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linksColumn';
          }
        | {
            /**
             * Column heading displayed above the social links.
             */
            heading: string;
            socials?:
              | {
                  platform: string;
                  url: string;
                  /**
                   * Override the default brand color or use a rounded badge style.
                   */
                  iconStyle?: {
                    variant?: ('default' | 'custom' | 'rounded') | null;
                    /**
                     * Hex, e.g. #ffffff
                     */
                    fill?: string | null;
                    /**
                     * Hex, e.g. #3b5998
                     */
                    background?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'socialColumn';
          }
        | {
            /**
             * Brand logo displayed at the top of the column.
             */
            logoImage?: (string | null) | Media;
            badgeEnabled?: boolean | null;
            /**
             * When set, overrides the built-in badge layout below.
             */
            badgeImage?: (string | null) | Media;
            badgeTitle?: string | null;
            badgeSubtitle?: string | null;
            rating?: number | null;
            googleReviewUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'badgeColumn';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  contactInfo: ContactInfo;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfo".
 */
export interface ContactInfo {
  email?: string | null;
  phone?: string | null;
  address: {
    street: string;
    suburb?: string | null;
    city: string;
    province: string;
    postCode?: string | null;
    mapsLink?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  headerLogo?: T;
  topNav?:
    | T
    | {
        homeLinkText?: T;
        topNavLinks?: T | NavLinksSelect<T>;
      };
  leftLinks?: T | NavLinksSelect<T>;
  rightLinks?: T | NavLinksSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NavLinks_select".
 */
export interface NavLinksSelect<T extends boolean = true> {
  type?: T;
  variant?: T;
  target?: T;
  label?: T;
  reference?: T;
  url?: T;
  parentLinkType?: T;
  children?:
    | T
    | {
        type?: T;
        label?: T;
        reference?: T;
        url?: T;
        id?: T;
      };
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyrightText?: T;
  bottomBarLink?: T | NavLinksSelect<T>;
  whatsappUrl?: T;
  newsletter?:
    | T
    | {
        enabled?: T;
        heading?: T;
        placeholder?: T;
        buttonLabel?: T;
        form?: T;
      };
  columns?:
    | T
    | {
        linksColumn?:
          | T
          | {
              heading?: T;
              links?: T | NavLinksSelect<T>;
              id?: T;
              blockName?: T;
            };
        socialColumn?:
          | T
          | {
              heading?: T;
              socials?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    iconStyle?:
                      | T
                      | {
                          variant?: T;
                          fill?: T;
                          background?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        badgeColumn?:
          | T
          | {
              logoImage?: T;
              badgeEnabled?: T;
              badgeImage?: T;
              badgeTitle?: T;
              badgeSubtitle?: T;
              rating?: T;
              googleReviewUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  contactInfo?: T | ContactInfoSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfo_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  address?:
    | T
    | {
        street?: T;
        suburb?: T;
        city?: T;
        province?: T;
        postCode?: T;
        mapsLink?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'blogs';
          value: string | Blog;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}